apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amc-deployment-${TARGET_ROLE}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: amc
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name: amc-container
        image: dcaro/amc:${AMC_WEB_VERSION}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
