kind: Service
apiVersion: v1
metadata:
  name: amc-service
  labels:
    app: amc
    role: ${TARGET_ROLE}
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: amc
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 80
