kind: Service
apiVersion: v1
metadata:
  name: amc-web-service
  labels:
    app: amc-web
    role: ${TARGET_ROLE}
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: amc-web
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 80
