kind: Service
apiVersion: v1
metadata:
  name: amc-web-test-${TARGET_ROLE}
  labels:
    app: amc-web
    role: test-${TARGET_ROLE}
spec:
  type: LoadBalancer
  selector:
    app: amc-web
    role: ${TARGET_ROLE}
  ports:
    - port: 80
      targetPort: 80
